###
POST http://localhost:3000/upload
Content-Type: application/json

{
  "gdriveUrl": "https://drive.google.com/file/d/1jacbf_dAdCYYzYd3ThgJXEMsjkmCQxuy/view"
}

//https://s3api.bucket.gulbadantaha.com/taha-bucket/demo.jpg?response-content-disposition=inline